apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-${LABEL_VERSION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
      version: ${LABEL_VERSION}
  template:
    metadata:
      labels:
        app: capstone-app
        version: ${LABEL_VERSION}
    spec:
      containers:
      - name: capstone-app
        image: ${DOCKER_IMAGE}
        ports:
        - containerPort: 80
